services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - api-gateway

  frontend:
    build: ./frontend
    depends_on:
      - api-gateway

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"

  api-gateway:
    build: ./services/api-gateway
    environment:
      PORT: 3000

      OIDC_ISSUER: http://keycloak:8080/realms/aigw
      OIDC_CLIENT_ID: aigw-frontend
      KEYCLOAK_TOKEN_URL: http://keycloak:8080/realms/aigw/protocol/openid-connect/token

      PROMPT_INSPECTOR_URL: http://prompt-inspector:3001
      RISK_ENGINE_URL: http://risk-engine:3002
      POLICY_ENGINE_URL: http://policy-engine:3003
      LOGGER_GRC_URL: http://logger-grc:3005
      LLM_URL: http://llm-mock:3006
    depends_on:
      - keycloak
      - prompt-inspector
      - risk-engine
      - policy-engine
      - response-analyzer
      - logger-grc
      - llm-mock

  prompt-inspector:
    build: ./services/prompt-inspector
    environment:
      PORT: 3001

  risk-engine:
    build: ./services/risk-engine
    environment:
      PORT: 3002

  policy-engine:
    build: ./services/policy-engine
    environment:
      PORT: 3003

  response-analyzer:
    build: ./services/response-analyzer
    environment:
      PORT: 3004

  logger-grc:
    build: ./services/logger-grc
    environment:
      PORT: 3005
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: aigw
      PGUSER: aigw
      PGPASSWORD: aigwpass
    depends_on:
      - postgres
      - elasticsearch

  llm-mock:
    build: ./services/llm-mock
    environment:
      PORT: 3006

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: aigw
      POSTGRES_USER: aigw
      POSTGRES_PASSWORD: aigwpass
    volumes:
      - ./infra/postgres/init:/docker-entrypoint-initdb.d

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m