export const DLP_PATTERNS = [
  {
    type: "Nom complet",
    severity: "MEDIUM",
    frameworks: ["RGPD", "ISO27001"],
    regex: /\b[A-ZÀ-Ÿ][a-zà-ÿ'-]{2,}\s+[A-ZÀ-Ÿ][a-zà-ÿ'-]{2,}\b/g,
  },
  {
    type: "Adresse email",
    severity: "HIGH",
    frameworks: ["RGPD", "NIS2", "ISO27001"],
    regex: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,
  },
  {
    type: "Téléphone",
    severity: "MEDIUM",
    frameworks: ["RGPD"],
    regex: /\b(?:\+32|0032|0)\s?[1-9](?:[\s.-]?\d{2}){3,4}\b/g,
  },
  {
    type: "Adresse",
    severity: "HIGH",
    frameworks: ["RGPD"],
    regex: /\b\d{1,4}\s+(?:rue|avenue|boulevard|chaussée|straat|laan|street|road|place)\s+[A-ZÀ-Ÿa-zà-ÿ0-9\s'-]{3,80}\b/gi,
  },
  {
    type: "Date de naissance",
    severity: "HIGH",
    frameworks: ["RGPD"],
    regex: /\b\d{1,2}[\/.-]\d{1,2}[\/.-]\d{2,4}\b/g,
  },
  {
    type: "Registre national",
    severity: "CRITICAL",
    frameworks: ["RGPD", "NIS2"],
    regex: /\b\d{2}[.\s-]?\d{2}[.\s-]?\d{2}[.\s-]?\d{3}[.\s-]?\d{2}\b/g,
  },
  {
    type: "Passeport",
    severity: "HIGH",
    frameworks: ["RGPD"],
    regex: /\b(?:passport|passeport)?\s*[:\-]?\s*[A-Z]{1,2}[0-9A-Z]{6,12}\b/gi,
  },
  {
    type: "IBAN",
    severity: "CRITICAL",
    frameworks: ["RGPD", "NIS2", "ISO27001"],
    regex: /\b[A-Z]{2}\d{2}(?:\s?[A-Z0-9]{4}){2,7}\b/g,
  },
  {
    type: "Carte bancaire",
    severity: "CRITICAL",
    frameworks: ["RGPD", "ISO27001"],
    regex: /\b(?:\d[ -]*?){13,19}\b/g,
  },
  {
    type: "CVV",
    severity: "CRITICAL",
    frameworks: ["RGPD", "ISO27001"],
    regex: /\b(?:CVV|CVC)\s*[:=]?\s*\d{3,4}\b/gi,
  },
  {
    type: "SWIFT/BIC",
    severity: "HIGH",
    frameworks: ["RGPD", "ISO27001"],
    regex: /\b[A-Z]{6}[A-Z0-9]{2}(?:[A-Z0-9]{3})?\b/g,
  },
  {
    type: "Facture",
    severity: "MEDIUM",
    frameworks: ["ISO27001"],
    regex: /\b(?:FACT|INV|INVOICE|FACTURE)[-_]?\d{4,}\b/gi,
  },
  {
    type: "Salaire",
    severity: "HIGH",
    frameworks: ["RGPD", "ISO27001"],
    regex: /\b(?:salaire|salary|bonus|payroll|rémunération)\s*[:\-]?\s*\d{2,7}(?:[,.]\d{2})?\s*(?:€|EUR|euros)?\b/gi,
  },

  {
    type: "API Key",
    severity: "CRITICAL",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:api[_-]?key|apikey|secret[_-]?key|client[_-]?secret)\s*[:=]\s*["']?[A-Za-z0-9_\-./=]{12,}["']?/gi,
  },
  {
    type: "AWS Secret",
    severity: "CRITICAL",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:AKIA|ASIA)[0-9A-Z]{16}\b/g,
  },
  {
    type: "JWT Token",
    severity: "CRITICAL",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/g,
  },
  {
    type: "Password",
    severity: "CRITICAL",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:password|passwd|pwd|motdepasse|mot_de_passe|secret)\s*[:=]\s*["']?[^\s,;"]+["']?/gi,
  },
  {
    type: "SSH Key",
    severity: "CRITICAL",
    frameworks: ["NIS2", "ISO27001"],
    regex:
      /-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----[\s\S]*?-----END (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----/g,
  },
  {
    type: "Kubernetes Secret",
    severity: "CRITICAL",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:k8s|kubernetes)[-_ ]?(?:secret|token)[-_ ]?[A-Za-z0-9_-]{6,}\b/gi,
  },

  {
    type: "Firewall",
    severity: "HIGH",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:firewall|palo alto|fortigate|checkpoint|cisco asa|allow_internal|deny_all)\b/gi,
  },
  {
    type: "Serveur critique",
    severity: "HIGH",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:srv|server|prod|production)[-_]?[a-zA-Z0-9_-]{3,}\b/gi,
  },
  {
    type: "SOC Incident",
    severity: "CRITICAL",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:soc alert|incident|ransomware|breach|compromise|privilege escalation)\b/gi,
  },
  {
    type: "OT/SCADA",
    severity: "CRITICAL",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:scada|plc|ics|ot segment|industrial control system|electrical grid controller)\b/gi,
  },
  {
    type: "VPN",
    severity: "HIGH",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:vpn|openvpn|wireguard|ipsec|vpn-core|vpn-admin)\b/gi,
  },
  {
    type: "SIEM",
    severity: "HIGH",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:siem|splunk|elastic siem|sentinel|qradar|soc dashboard)\b/gi,
  },

  {
    type: "Projet confidentiel",
    severity: "HIGH",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:projet|project)\s+[A-Za-z0-9_-]{3,}\s*(?:confidentiel|confidential|secret|internal)?\b/gi,
  },
  {
    type: "Code source",
    severity: "CRITICAL",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:function|const|let|var|class|public static|private static|SELECT \* FROM|INSERT INTO|masterPassword|password\s*=)\b/gi,
  },
  {
    type: "Architecture",
    severity: "HIGH",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:architecture|zero trust|microservices|kubernetes|hybrid cloud|hld|lld|topology)\b/gi,
  },
  {
    type: "Roadmap",
    severity: "HIGH",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:roadmap|strategy|stratégie|acquisition strategy|future release|internal planning)\b/gi,
  },

  {
    type: "Prompt Injection",
    severity: "CRITICAL",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:ignore previous instructions|ignore all previous|override instructions|disregard rules)\b/gi,
  },
  {
    type: "Jailbreak",
    severity: "CRITICAL",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:dan mode|developer mode|jailbreak|unrestricted ai|no restrictions|do anything now)\b/gi,
  },
  {
    type: "Data Exfiltration",
    severity: "CRITICAL",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:export all|extract all|dump database|send all credentials|retrieve secrets|export all passwords)\b/gi,
  },
  {
    type: "System Prompt Leak",
    severity: "CRITICAL",
    frameworks: ["NIS2", "ISO27001"],
    regex: /\b(?:show system prompt|reveal hidden prompt|display internal instructions|show developer prompt|reveal your system prompt)\b/gi,
  },
];

export const BUSINESS_KEYWORDS = [
  "confidentiel",
  "confidential",
  "strictement confidentiel",
  "internal only",
  "restricted",
  "secret",
  "contrat",
  "contract",
  "salaire",
  "salary",
  "licenciement",
  "client stratégique",
  "fournisseur",
  "supplier",
  "offre commerciale",
  "appel d'offre",
  "pricing",
  "roadmap",
  "stratégie",
  "strategy",
  "architecture interne",
  "incident sécurité",
  "security incident",
  "vulnérabilité",
  "vulnerability",
  "audit",
  "NIS2",
  "ISO27001",
  "DORA",
  "GDPR",
  "RGPD",
  "EU AI Act",
];